export default {
  'Action': 'Acción',
  'Actions': 'Acciones',
  'Carrer': 'Carrera',
  'Course': 'Curso',
  'Courses': 'Cursos',
  'Home': 'Inicio',
  'Students': 'Estudiantes',
  'Loading': 'Cargando',
  'Id': 'Código',
  'Code': 'Código',
  'Name': 'Nombre',
  'Course Template': 'Plantilla de Curso',
  'Course Templates': 'Plantillas de Curso',
  'Submit': 'Enviar',
  'URL': 'URL',
  'enter Username': 'Ingrese nombre de usuario',
  'enter Password': 'Ingrese contraseña',
  'Username': 'Nombre de Usuario',
  'Password': 'Contraseña',
  'Error has occurred': 'Ha ocurrido un error',
  'Return to the first page': 'Volver a primera página',
}
